### ISSUE TITLE
Captcha

### ISSUE THREAD

**Issue by yparent** [x3rus/training#2]
Bonjour,
Je cherche à me créer un compte sur votre site : http://moodle.x3rus.com/ pour avoir le contenu du cours devops en entier avec les outils mais le captcha ne fonctionne plus donc impossible de créer un compte.
Merci d'avance.

**Comment by x3rus** [comment]
Bonjour,
Bon j'ai finalement un peu de temps pour répondre , merci d'avoir signalé le problème pour moodle , je vais faire le correctif ... un jour :P , je vais conservé le billet ouvert . 

Cependant le contenu de la formation DevOps n'est PAS sur moodle .. ou du moins ne fut pas conservé à jour . 
Voici les liens : 

* Intro DevOps : https://github.com/x3rus/training/blob/master/devops/01-introduction.md
* Jenkins : https://github.com/x3rus/training/tree/master/jenkins
* Gitlab : https://github.com/x3rus/training/blob/master/gitlab/01-presentation.md

Bonne journée

**Comment by yparent** [comment]
Merci ;-)

**Comment by x3rus** [comment]
Le problème est corrigé  :) j'ai mis à jour le service moodle et ré-importé le cours et users .
le manque de temps fait que j'y ai pas mis beaucoup d'amour .
